### ISSUE TITLE
[Game Request] D.C.5 ~Da Capo 5~

### ISSUE THREAD

**Issue by Delta658** [crskycode/GARbro#12]
Download Link:https://stuqhnueducn-my.sharepoint.com/:u:/g/personal/cuiyue4703_stu_qhnu_edu_cn/EQq-JMGTcG9EpFd0D6_YLn4BC0ow9tPsgX82JEeNW5lKeA?e=8s9Yg6
Password:0721

VNDB:https://vndb.org/v36687
Developer:CIRCUS
Engine:krkr
The zipped files are encrypted.
I would like to request that you decrypt it.

**Comment by crskycode** [comment]
https://github.com/crskycode/GARbro/commit/c6d8e7c4238a3022b82296d66051e247a4849871

**Comment by Delta658** [comment]
I spent some time downloading the latest database and trying to extract files from D.C.5-Da Capo 5~, but I found that it still cannot be decrypted (even if I have already selected D.C.5-Da Capo 5~in GARbro)

**Comment by Delta658** [comment]
> [c6d8e7c](https://github.com/crskycode/GARbro/commit/c6d8e7c4238a3022b82296d66051e247a4849871)

I spent some time downloading the latest database and trying to extract files from D.C.5-Da Capo 5~, but I found that it still cannot be decrypted (even if I have already selected D.C.5-Da Capo 5~in GARbro)

**Comment by crskycode** [comment]
> > [c6d8e7c](https://github.com/crskycode/GARbro/commit/c6d8e7c4238a3022b82296d66051e247a4849871)
> 
> I spent some time downloading the latest database and trying to extract files from D.C.5-Da Capo 5~, but I found that it still cannot be decrypted (even if I have already selected D.C.5-Da Capo 5~in GARbro)

You can't get correct file name via GARbro-Mod
