### ISSUE TITLE
[Game Request] Clover Day's Plus （2023）

### ISSUE THREAD

**Issue by alittlered** [crskycode/GARbro#13]
VNDB:
https://vndb.org/r109474
https://vndb.org/r33209
https://vndb.org/r111892

The files are encrypted.

**Comment by crskycode** [comment]
https://github.com/YeLikesss/CNGALTools/tree/main/998.HikariField/NekoNyan

**Comment by alittlered** [comment]
> https://github.com/YeLikesss/CNGALTools/tree/main/998.HikariField/NekoNyan

thx
