### ISSUE TITLE
GINKA, the file names appear as garbled characters.

### ISSUE THREAD

**Issue by bfloat16** [crskycode/GARbro#14]
In GINKA's xp3 package, all file names appear as garbled characters, but the files can be read normally. What should I do to restore the file names? (I heard that the garbled characters are caused by krkrZ using hashed file names?)
<img width="252" alt="image" src="https://github.com/crskycode/GARbro/assets/38366253/062eff99-1ff9-4ca9-8b8d-e9df77664e0a">
<img width="673" alt="image" src="https://github.com/crskycode/GARbro/assets/38366253/41995f0d-431b-4143-b4b6-290f45935daf">

**Comment by Silicon7921** [comment]
I dont think there is a simple way to find the original file names, since the names may be encrypted.

**Comment by crskycode** [comment]
GARbro can't resolve filenames from this type XP3 file. Because what is stored in the XP3 file is a hash value of the original filename, not the filename itself. GARbro cannot reverse the hash.

To get the file names, you need to use KrkrDump, a tool that extracts files read by the game engine in real time. However, please note that it cannot extract all files at once.

**Comment by Cosetto** [comment]
[HxNames.zip](https://github.com/crskycode/GARbro/files/13402021/HxNames.zip)
@bfloat16 Place this in GameData folder of GARbro mod. This will cover most of Ginka's file

**Comment by Silicon7921** [comment]
> [HxNames.zip](https://github.com/crskycode/GARbro/files/13402021/HxNames.zip) @bfloat16 Place this in GameData folder of GARbro mod. This will cover most of Ginka's file

omg thanks

**Comment by Nutori3** [comment]
> HxCrypt creation method is not supported in GARbro mod. To create patch for HxCrypt, use the latest version.dll(92kb) and xp3pack to create unencrypted.xp3

I repeat: when using version.dll and Xp3Pack, the patch is created, but the game does not accept the changes.

**Comment by Nutori3** [comment]
Thank you!

**Comment by Nutori3** [comment]
HxNames extract only 4 story files. There's obviously mor
![Снимок](https://github.com/crskycode/GARbro/assets/137778917/e3d0e8d8-4b89-456c-a63b-518cdea32b6d)
e.

**Comment by Cosetto** [comment]
> Thank you very much, but I still want to ask, how should I find the hash and compare the real file name?
[krkrdump.zip](https://github.com/crskycode/GARbro/files/13622692/krkrdump.zip)
This will dump a .log file, then use [link](https://github.com/crskycode/GenHxHashList) to generate HxNames.lst from that .log file

**Comment by bfloat16** [comment]
> > Thank you very much, but I still want to ask, how should I find the hash and compare the real file name?
> 
> [krkrdump.zip](https://github.com/crskycode/GARbro/files/13622692/krkrdump.zip) This will dump a .log file, then use [link](https://github.com/crskycode/GenHxHashList) to generate HxNames.lst from that .log file

Thank you, got it : )

**Comment by Nutori3** [comment]
> HxNames extract only 5 story files. There's obviously more.

How did you solve this problem?

**Comment by Cosetto** [comment]
Use krkrdump and run through the game. They scripts will be extracted eventually

**Comment by Nutori3** [comment]
https://drive.google.com/file/d/1tcV_qjAPUhS08AyvTCQ-lr9ILsaKCIry/view?usp=sharing

Inserted Russian text (not going through editing) into the game and sorted out the scripts. But, as you can see, buttons "auto", "skip", "log" (and a bunch of buttons in settings) are not translated. They are in pbd format, how to work with them?
![TebUntmsQvE](https://github.com/crskycode/GARbro/assets/137778917/812258c5-5c69-436f-b801-8f2ecb900c57)

**Comment by Walkedharmony** [comment]
> https://drive.google.com/file/d/1tcV_qjAPUhS08AyvTCQ-lr9ILsaKCIry/view?usp=sharing
> 
> Inserted Russian text (not going through editing) into the game and sorted out the scripts. But, as you can see, buttons "auto", "skip", "log" (and a bunch of buttons in settings) are not translated. They are in pbd format, how to work with them? ![TebUntmsQvE](https://private-user-images.githubusercontent.com/137778917/289308681-812258c5-5c69-436f-b801-8f2ecb900c57.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTQ4MjMsIm5iZiI6MTcwNjAxNDUyMywicGF0aCI6Ii8xMzc3Nzg5MTcvMjg5MzA4NjgxLTgxMjI1OGM1LTVjNjktNDM2Zi1iODAxLThmMmVjYjkwMGM1Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxMjU1MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzY0OTY3YTRjY2U4ZGVmNzRkM2ZlODBhMDMxYzJiNGQyMjg2NzIxODUzZWM2MmQ0YjEyNmZiYjExYzk0NTEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5JITkCY5zV7msdUQhYVquX8cY8OE7X4lI5nY72Zw6wQ)

How many scn files are there in total on the Ginka VN? I only got 18 files, is that all or nothing?

**Comment by bfloat16** [comment]
> > https://drive.google.com/file/d/1tcV_qjAPUhS08AyvTCQ-lr9ILsaKCIry/view?usp=sharing
> > Inserted Russian text (not going through editing) into the game and sorted out the scripts. But, as you can see, buttons "auto", "skip", "log" (and a bunch of buttons in settings) are not translated. They are in pbd format, how to work with them? ![TebUntmsQvE](https://private-user-images.githubusercontent.com/137778917/289308681-812258c5-5c69-436f-b801-8f2ecb900c57.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTQ4MjMsIm5iZiI6MTcwNjAxNDUyMywicGF0aCI6Ii8xMzc3Nzg5MTcvMjg5MzA4NjgxLTgxMjI1OGM1LTVjNjktNDM2Zi1iODAxLThmMmVjYjkwMGM1Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxMjU1MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzY0OTY3YTRjY2U4ZGVmNzRkM2ZlODBhMDMxYzJiNGQyMjg2NzIxODUzZWM2MmQ0YjEyNmZiYjExYzk0NTEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5JITkCY5zV7msdUQhYVquX8cY8OE7X4lI5nY72Zw6wQ)
> 
> How many scn files are there in total on the Ginka VN? I only got 18 files, is that all or nothing?

Total 37 files
![image](https://github.com/crskycode/GARbro/assets/38366253/d8b0c3e5-4454-43d8-82f3-344b9210b558)

**Comment by Walkedharmony** [comment]
> > > https://drive.google.com/file/d/1tcV_qjAPUhS08AyvTCQ-lr9ILsaKCIry/view?usp=sharing
> > > Inserted Russian text (not going through editing) into the game and sorted out the scripts. But, as you can see, buttons "auto", "skip", "log" (and a bunch of buttons in settings) are not translated. They are in pbd format, how to work with them? ![TebUntmsQvE](https://private-user-images.githubusercontent.com/137778917/289308681-812258c5-5c69-436f-b801-8f2ecb900c57.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTQ4MjMsIm5iZiI6MTcwNjAxNDUyMywicGF0aCI6Ii8xMzc3Nzg5MTcvMjg5MzA4NjgxLTgxMjI1OGM1LTVjNjktNDM2Zi1iODAxLThmMmVjYjkwMGM1Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxMjU1MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzY0OTY3YTRjY2U4ZGVmNzRkM2ZlODBhMDMxYzJiNGQyMjg2NzIxODUzZWM2MmQ0YjEyNmZiYjExYzk0NTEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5JITkCY5zV7msdUQhYVquX8cY8OE7X4lI5nY72Zw6wQ)
> > 
> > 
> > How many scn files are there in total on the Ginka VN? I only got 18 files, is that all or nothing?
> 
> Total 37 files ![image](https://private-user-images.githubusercontent.com/38366253/298959430-d8b0c3e5-4454-43d8-82f3-344b9210b558.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTc5MDgsIm5iZiI6MTcwNjAxNzYwOCwicGF0aCI6Ii8zODM2NjI1My8yOTg5NTk0MzAtZDhiMGMzZTUtNDQ1NC00M2Q4LTgyZjMtMzQ0YjkyMTBiNTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEzNDY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4OTBiY2M5YjllMDA1NTJiMWQxZTQ3NjI2MWRlZDJkMWE2ZjRiNzIyOTRhMDk2ZjQ2ZmQ2MGZkYWNkNjc4ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OoxYWkX1x2rPsXWqV4b6R3bP-vk52iOX2el6n_lhAjo)

Oh man it's a lot more than I thought, thanks for answering so quickly. If it is allowed to share the scn file, I am also very helpful and grateful.

**Comment by Walkedharmony** [comment]
> https://drive.google.com/file/d/1tcV_qjAPUhS08AyvTCQ-lr9ILsaKCIry/view?usp=sharing
> 
> Inserted Russian text (not going through editing) into the game and sorted out the scripts. But, as you can see, buttons "auto", "skip", "log" (and a bunch of buttons in settings) are not translated. They are in pbd format, how to work with them? ![TebUntmsQvE](https://private-user-images.githubusercontent.com/137778917/289308681-812258c5-5c69-436f-b801-8f2ecb900c57.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNzM4NTIsIm5iZiI6MTcwNjM3MzU1MiwicGF0aCI6Ii8xMzc3Nzg5MTcvMjg5MzA4NjgxLTgxMjI1OGM1LTVjNjktNDM2Zi1iODAxLThmMmVjYjkwMGM1Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QxNjM5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMTNmZDg2MzhhYmMzMjA2OTg0OTgxNDA1MGVmZTdiZTRlZDI4ODQ3NjU4MGRjZjhiNDUzY2I1MTY5MWIyMzBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MIY--_1miNAIV_QMeOpy0bTgb8xNbNjgKCVJ90FgEDk)

Have you been able to solve that problem? If not, I have a solution.

**Comment by Nutori3** [comment]
> > https://drive.google.com/file/d/1tcV_qjAPUhS08AyvTCQ-lr9ILsaKCIry/view?usp=sharing
> > Inserted Russian text (not going through editing) into the game and sorted out the scripts. But, as you can see, buttons "auto", "skip", "log" (and a bunch of buttons in settings) are not translated. They are in pbd format, how to work with them? ![TebUntmsQvE](https://private-user-images.githubusercontent.com/137778917/289308681-812258c5-5c69-436f-b801-8f2ecb900c57.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNzM4NTIsIm5iZiI6MTcwNjM3MzU1MiwicGF0aCI6Ii8xMzc3Nzg5MTcvMjg5MzA4NjgxLTgxMjI1OGM1LTVjNjktNDM2Zi1iODAxLThmMmVjYjkwMGM1Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QxNjM5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMTNmZDg2MzhhYmMzMjA2OTg0OTgxNDA1MGVmZTdiZTRlZDI4ODQ3NjU4MGRjZjhiNDUzY2I1MTY5MWIyMzBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MIY--_1miNAIV_QMeOpy0bTgb8xNbNjgKCVJ90FgEDk)
> 
> Have you been able to solve that problem? If not, I have a solution.
> 
> by using krkrtpc.exe

I solved this problem a long time ago, but thanks. Now the only thing left is to adjust the Russian text in the graphics to the ideal size, so that it doesn't look crooked, as, for example, it did in the main menu. Especially pay attention to the "Выход" (exit button). 

It is extremely inconvenient to work with graphics in this form. But I don't think there is a programme that allows you to remove at least the magenta borders here, let alone make a separate file for each button, as it was in ATRI My Dear Moments. (I worked there in FreeMoteToolKit, and the format of the graphics files was .psb.

![Снимок1](https://github.com/crskycode/GARbro/assets/137778917/ab728aa4-4c7e-40c2-ab84-142f5f911feb)
![6972](https://github.com/crskycode/GARbro/assets/137778917/771d8b02-7ca8-4ae8-8e0d-29ffd36bed2b)
![15](https://github.com/crskycode/GARbro/assets/137778917/b389605c-af50-4740-9088-b49aef2e4ccd)

**Comment by Nutori3** [comment]
> > > > https://drive.google.com/file/d/1tcV_qjAPUhS08AyvTCQ-lr9ILsaKCIry/view?usp=sharing
> > > > Teks Rusia yang dimasukkan (tidak melalui pengeditan) ke dalam game dan memilah skrip. Tapi, seperti yang Anda lihat, tombol "otomatis", "lewati", "log" (dan banyak tombol dalam pengaturan) tidak diterjemahkan. Mereka dalam format pbd, bagaimana cara bekerja dengan mereka? ![TebUntmsQvE](https://private-user-images.githubusercontent.com/137778917/289308681-812258c5-5c69-436f-b801-8f2ecb900c57.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNzM4NTIsIm5iZiI6MTcwNjM3MzU1MiwicGF0aCI6Ii8xMzc3Nzg5MTcvMjg5MzA4NjgxLTgxMjI1OGM1LTVjNjktNDM2Zi1iODAxLThmMmVjYjkwMGM1Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QxNjM5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMTNmZDg2MzhhYmMzMjA2OTg0OTgxNDA1MGVmZTdiZTRlZDI4ODQ3NjU4MGRjZjhiNDUzY2I1MTY5MWIyMzBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MIY--_1miNAIV_QMeOpy0bTgb8xNbNjgKCVJ90FgEDk)
> > > 
> > > 
> > > Apakah Anda bisa menyelesaikan masalah itu? Jika tidak, saya punya solusi.
> > > dengan menggunakan krkrtpc.exe
> > 
> > 
> > Saya sudah memecahkan masalah ini sejak lama, tapi terima kasih. Program krkrtpc.exe membantu saat itu. Sekarang satu-satunya yang tersisa adalah menyesuaikan teks Rusia dalam grafik dengan ukuran yang ideal, sehingga tidak terlihat bengkok, seperti, misalnya, yang terjadi di menu utama. Terutama memperhatikan "Выход" (tombol keluar).
> > Sangat tidak nyaman bekerja dengan grafik dalam bentuk ini. Tapi saya tidak berpikir ada program yang memungkinkan Anda untuk menghapus setidaknya batas magenta di sini, apalagi membuat file terpisah untuk setiap tombol, seperti di ATRI My Dear Moments. (Saya bekerja di sana di FreeMoteToolKit, dan format file grafik adalah .psb.)
> > ![Снимок1](https://private-user-images.githubusercontent.com/137778917/300199471-ab728aa4-4c7e-40c2-ab84-142f5f911feb.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNjkzMjAsIm5iZiI6MTcwNzM2OTAyMCwicGF0aCI6Ii8xMzc3Nzg5MTcvMzAwMTk5NDcxLWFiNzI4YWE0LTRjN2UtNDBjMi1hYjg0LTE0MmY1ZjkxMWZlYi5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQwNTEwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTBiMjNjMDhhY2QxZDc3MGM3NWY3YzZmMTQ3YTc5NjQzMDQ1OWIwODQ5OTA1MWFjNjBlOTg2MmUwMzM5OTQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4kaNDPBV4Duh1LJ1sS6vvmj0sv01WIxYHWBpw7yID90) ![6972](https://private-user-images.githubusercontent.com/137778917/300198706-771d8b02-7ca8-4ae8-8e0d-29ffd36bed2b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNjkzMjAsIm5iZiI6MTcwNzM2OTAyMCwicGF0aCI6Ii8xMzc3Nzg5MTcvMzAwMTk4NzA2LTc3MWQ4YjAyLTdjYTgtNGFlOC04ZTBkLTI5ZmZkMzZiZWQyYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQwNTEwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTBmMzYyZGIxNzcxNjhmZjhhYzlkOWUxNWZlNTJmNmY1ZjI4ZmRkZDRiZDBmOGJhMjcxZjhmMjk5MTY0NjhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-dp5lKpES1DZ_7heja5KQ3-W1xuAJP6ElkNj0G0A7Ws) ![15](https://private-user-images.githubusercontent.com/137778917/300198711-b389605c-af50-4740-9088-b49aef2e4ccd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNjkzMjAsIm5iZiI6MTcwNzM2OTAyMCwicGF0aCI6Ii8xMzc3Nzg5MTcvMzAwMTk4NzExLWIzODk2MDVjLWFmNTAtNDc0MC05MDg4LWI0OWFlZjJlNGNjZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQwNTEwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTc3ZGM0N2U5MGE4MjEwYjFlOWEwMTc5ZjhlYWJmMGYzODZmYTQ4ZjY4MTA3OTk4OWU2ZDU3NGU0NzlmY2FhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W59wyeG2u7hAmjlUQeMldaxghM-6k1ZUVNw6U6D9tac)
> 
> Have you tried GINKA version 1.03? Because the content is different

"Patch Update

（ver. 1.03)

– added Traditional Chinese language support
– adjustment to the option menu interface
– fixed a display issue of the menu bar
– fixed a few minor visual issues
– fixed an issue regarding the screenshot thumbnails which displayed a different image from the screenshot (Steam ver. only)"

I bought it on Steam a week ago. Just opened the graphic files now - they look identical. I saw the list of changes here: http://ginka.frontwing.jp/en_news/ginka-update_date-en/
