### ISSUE TITLE
Allow repacking SakanaGL files

### ISSUE THREAD

**Issue by RTH-Retribution** [crskycode/GARbro#20]
Allow us to repack Cyberstep SakanaGL (SX) & (SXStorage) files so improvements to music or implementation of improved art can actually be utilised by the games.

**Comment by crskycode** [comment]
This package format used by different versions of the engine varies so much that I can't offer a generic solution.

**Comment by RTH-Retribution** [comment]
> This package format used by different versions of the engine varies so much that I can't offer a generic solution.

could i attach the specific file from the specific VN itself since its only really the mischief dungeon life clara edition im looking to patch?
