### ISSUE TITLE
Replaced by Latest database issue

### ISSUE THREAD

**Issue by XYumetian** [crskycode/GARbro#21]
While I replace the former database with the latest, no other choices except nocrypt on the screen. What's the problem? Appreciate for the support.

**Comment by XYumetian** [comment]
1. I download the latest GBAbro 1.5.44 from this url: https://github.com/morkt/GARbro/release;
2. And download the database file from https://github.com/crskycode/GARbro/blob/master/ArcFormats/Resources/Formats.dat.
Thx!!

**Comment by crskycode** [comment]
Downlaod GARbro-Mod from [here](https://github.com/crskycode/GARbro/releases) should works.
