### ISSUE TITLE
[Game Request] 我が姫君に栄冠を

### ISSUE THREAD

**Issue by Ptilopsis01** [crskycode/GARbro#23]
https://vndb.org/v29057
The .dat patches of this game can be correctly opened with any encryption chosen, 
<img width="842" alt="image" src="https://github.com/crskycode/GARbro/assets/93318731/d276ecae-9ae8-4af6-84d6-7bd741c95331">
but none of them can fully unpack all CGs.

**Comment by Cosetto** [comment]
This engine needs a file list just like Wamsoft. But there's an alternative way to extract the cgs.
Use this dll
[dsound.zip](https://github.com/crskycode/GARbro/files/14075089/dsound.zip)
Place it in the same folder with the .exe, but you need to remove sdwrap from the exe first.
Now just run through the game, all the file in arcx.dat will be extracted to "Dump" folder

**Comment by Cosetto** [comment]
Here https://drive.google.com/file/d/1kRvS8PsS0DDv1_Thg2YbwblFAH5oLyw9/view?usp=sharing

**Comment by Ptilopsis01** [comment]
Thanks!
