### ISSUE TITLE
Ego's Spark 18+ DLC 

### ISSUE THREAD

**Issue by Walkedharmony** [crskycode/GARbro#25]
Need a solution for manual update since GarBRO Mod is not currently supported for this VN: 

https://vndb.org/v37252

So I spent the whole day learning how to update format.dat and can rebuild but can't add updates myself, I'm still confused about cxdec or tpm and others.

**Comment by Cosetto** [comment]
Example: [link](https://github.com/satan53x/GARbro/blob/master/SchemeTool/Program.cs)

**Comment by Walkedharmony** [comment]
> Contoh: [link](https://github.com/satan53x/GARbro/blob/master/SchemeTool/Program.cs) Tapi game itu menggunakan Wamsoft (enkripsi Hx) dan lebih rumit dari Cxdex, jadi menurut saya Anda tidak bisa mengatasinya.

Is it still possible to follow this [tutorial](https://github.com/imKota/GalgameCoding/blob/2eca03d5ce121c84200eaf02ad5ee392e21f524b/Kirikiri/HowToFindCxEncryptKey/FindCxdecKey_CN.md?plain=1)?

**Comment by Cosetto** [comment]
Nope, that is for Cx encryption only. Recently, newer krkrz games use Hx Encrytion, like the game you mention and Ginka.

**Comment by Walkedharmony** [comment]
> Nope, that is for Cx encryption only. Recently, newer krkrz games use Hx Encrytion, like the game you mention and Ginka. Anyway, Crsky had added this https://vndb.org/v37252

Really? Where?

**Comment by Cosetto** [comment]
![image](https://github.com/crskycode/GARbro/assets/81801486/fb309fca-7217-40d2-8e3b-cfb6bb0366a3)
You didn't see this?
https://github.com/crskycode/GARbro/blob/master/ArcFormats/Resources/Formats.dat

**Comment by Walkedharmony** [comment]
> ![image](https://private-user-images.githubusercontent.com/81801486/307050151-fb309fca-7217-40d2-8e3b-cfb6bb0366a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MTYxNzYsIm5iZiI6MTcwODYxNTg3NiwicGF0aCI6Ii84MTgwMTQ4Ni8zMDcwNTAxNTEtZmIzMDlmY2EtNzIxNy00MGQyLThlM2ItY2ZiNmJiMDM2NmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE1MzExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlOGE1OTU3OGFhOTcwMTZhY2IwYTdkODBhYTdiMjJiMzFkNmI0OWQ1YzEwNGFlZjBiZThkMzhiNTBmNGE4YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vICrDelko9MtKPnZesfviVl_47JXA_jjnz5mYG6Xooo) Anda tidak melihat ini? https://github.com/crskycode/GARbro/blob/master/ArcFormats/Resources/Formats.dat

It was just updated so I don't know but thank you for answering my question

**Comment by Walkedharmony** [comment]
[HxNames.zip](https://github.com/crskycode/GARbro/files/14376804/HxNames.zip) This file already shows some of them 
![Screenshot 2024-02-22 234806](https://github.com/crskycode/GARbro/assets/157404664/fd7df406-76dd-4336-a58d-76f3a85bbe2f)
