### ISSUE TITLE
透明世界-CLEARWORLD | The data content cannot be read.

### ISSUE THREAD

**Issue by Walkedharmony** [crskycode/GARbro#27]
Title : CLEARWORLD -クリアワールド- 
Engine : Kirikiri Z 
VNDB : [v28646](https://vndb.org/v28646)

Even though this visual novel is not encrypted and can be extracted normally with GarBRO, the contents of all the data cannot be read.

Is there any solution? I tried using [krkrextract](https://github.com/xmoezzz/KrkrzExtract) to extract it but the contents of the file still couldn't be read. 

![Screenshot 2024-03-01 230454](https://github.com/crskycode/GARbro/assets/157404664/44f94895-b93e-46e4-afb6-953e6f6473f2)

**Comment by Cosetto** [comment]
![image](https://github.com/crskycode/GARbro/assets/81801486/af01fb2a-73d9-4202-be21-621705139162)
You sure? Cuz GARbro can read it normally

**Comment by mailwl** [comment]
please, remove links to pirated content

**Comment by Walkedharmony** [comment]
> please, remove links to pirated content

Sure
