### ISSUE TITLE
[Game Request] Tenshi☆Souzou RE-BOOT!

### ISSUE THREAD

**Issue by Rumia-Channel** [crskycode/GARbro#28]
Requesting support for unpacking .xp3 files from Tenshi☆Souzou RE-BOOT! (天使☆騒々 RE-BOOT!) https://vndb.org/v40520

I tried versions 5.0.0.2 and 4.0.1.5 of Kirikiri Extract but could not successfully unpack.

I tried to unencrypt to play this game on Kirikiroid 2, but the yuzu key I had been able to use did not work. 
I think that perhaps the encryption has changed since "Cafe Stella".
![image](https://github.com/crskycode/GARbro/assets/52584487/d9699daf-a8af-4c08-878f-13288b5250e2)
![image](https://github.com/crskycode/GARbro/assets/52584487/39690987-04d5-4921-9b15-fe933ca5b734)
![image](https://github.com/crskycode/GARbro/assets/52584487/9efc21ef-9ff4-447a-bae6-88d26f2701b1)
![image](https://github.com/crskycode/GARbro/assets/52584487/bbe8ca3a-5cd9-42d4-9b84-16f7f828ef33)

**Comment by Cosetto** [comment]
https://github.com/crskycode/KrkrDump
Wamsoft = use krkrdump

**Comment by Rumia-Channel** [comment]
So it is a specification that the folder structure is not maintained...
I wanted to maintain the folder structure in order to load it into Kirikiroid2, but it seems to be difficult...
Thank you very much.

**Comment by Cosetto** [comment]
Someone has made it playable on kirikiroid2, in fact, they found way for kirikiroid2 to read Wamsoft encryption

**Comment by Rumia-Channel** [comment]
> Someone has made it playable on kirikiroid2, in fact, they found way for kirikiroid2 to read Wamsoft encryption

Does that mean that if I can create krz_xp3conv.key, there is a high possibility that it will work properly?
Or does this mean that the Tenshi ☆ Souzou RE-BOOT! patch has already been completed in the closed community?

I'm not good at English, so I may not be able to understand the meaning correctly.

**Comment by Cosetto** [comment]
I remembered it related to .pdb file or something, and yeah, they don't share it to stranger.

**Comment by Refrain69** [comment]
@Cosetto 
How does this version be made?
I found the files inside can be read correctly with "no encryption" by Garbro.
And there is even the "steam" folder? IIRC,Tenshi☆Souzou RE-BOOT! hasn't released on Steam yet.

**Comment by Refrain69** [comment]
Maybe a leak or something?

**Comment by Cosetto** [comment]
It's Japanese version ofc

**Comment by Refrain69** [comment]
in data.xp3

**Comment by Refrain69** [comment]
Maybe this version
<img width="1077" alt="屏幕截图 2024-03-22 085255" src="https://github.com/crskycode/GARbro/assets/121091208/a18c073a-4465-4e62-b1f9-860f2ac731c5">

**Comment by Cosetto** [comment]
They ported it from another Cafe stella or something, it's their method so I don't really know.

**Comment by Refrain69** [comment]
wired……
also I noticed [this](https://galgame.download/beta/ambitious.html) last year.
Maybe it suggests a probability to transform Wamsoft encryption into something more familiar to us.

**Comment by Refrain69** [comment]
@Rumia-Channel How to get this?
![314180682-bbe8ca3a-5cd9-42d4-9b84-16f7f828ef33](https://github.com/crskycode/GARbro/assets/121091208/0c7b39e4-1fbd-4e08-aebc-7289cd5bbf19)

**Comment by Rumia-Channel** [comment]
@Refrain69 
I am a Japanese user and bought it through an authorised mail order service.
If you are referring to the version information on this screen, I just added -about  in the startup options. That is overlaid on the game screen.

**Comment by Refrain69** [comment]
Thanks.This is what i want.
