### ISSUE TITLE
First time trying to use this version, can't open archive files.

### ISSUE THREAD

**Issue by Vincent-Dawn** [crskycode/GARbro#36]
I'm having some trouble using this, whenever I click on an archive file on any game I keep getting "Name.File Type: file could not be opened as resource archive". I have the original Garbro and it lets me open or asks what type of encryption the file uses, but this one doesn't and I don't know what I'm doing wrong.

I'm trying to use this version to access the files for [Shiniyuku Kishi, Isekai ni Hibiku Danmatsuma](https://vndb.org/v49274). I also tried using KrkrExtract but I keep getting "internal error" followed by "failed to decompress special chunk".

**Comment by Vinfall** [comment]
Try [KrkrDump](https://github.com/crskycode/KrkrDump)
