### ISSUE TITLE
[GAME REQUEST]: Bishoujo Mangekyou Ibun - Yuki Onna.

### ISSUE THREAD

**Issue by wamiscorner** [crskycode/GARbro#40]
Hello, I've been trying to rip the sprites/cgs of this game for the longest time ever since it came out.
Garbro can open the .PACK file, but can't read the images inside ('Invalid Format'). I've updated the database as well, but it still does not work ; v ;

[HERE IS THE LINK TO THE FILE](https://drive.google.com/file/d/1Uksu1xWxbdUz-zRjPUm6ET8bGeSa6GJW/view?usp=sharing) (IN CASE THAT HELPS).

I would really appreciate the help, the art is so pretty!
Thank you so much ; v ;

**Comment by Cosetto** [comment]
[GARbro.zip](https://github.com/user-attachments/files/16686739/GARbro.zip)

**Comment by wamiscorner** [comment]
@Cosetto It still doesn't work sadly :(

**Comment by Cosetto** [comment]
Normal for me.
![image](https://github.com/user-attachments/assets/cd0eb947-2a39-41e0-9e66-32104b2ecea7)
Perhaps you move the .pack files to somewhere else? You need to remain it in GameData folder because GARbro can only read the files from there.

**Comment by Huyvux12** [comment]
> Hello, I've been trying to rip the sprites/cgs of this game for the longest time ever since it came out. Garbro can open the .PACK file, but can't read the images inside ('Invalid Format'). I've updated the database as well, but it still does not work ; v ;
> 
> [HERE IS THE LINK TO THE FILE](https://drive.google.com/file/d/1Uksu1xWxbdUz-zRjPUm6ET8bGeSa6GJW/view?usp=sharing) (IN CASE THAT HELPS).
> 
> I would really appreciate the help, the art is so pretty! Thank you so much ; v ;

How do you repack data.pack?

**Comment by Cosetto** [comment]
> How do you repack data.pack?

Somebody is already working on it [link](https://vndb.org/r122479)

**Comment by Huyvux12** [comment]
not me, but i know that guy

**Comment by wamiscorner** [comment]
@Cosetto That's so strange. I have the full game/same folders.
I don't know why it is not working lol.
