### ISSUE TITLE
Could I repacking .pack file with GARbro?

### ISSUE THREAD

**Issue by Huyvux12** [crskycode/GARbro#41]
I have unpacked the .pack file and edited the content inside, now I don't know how to repack it, please help me!!!!

**Comment by Cosetto** [comment]
Like said in other issue, someone is already working on it, it'll be released soon.

**Comment by ZKENSS** [comment]
use arc_conv []()https://github.com/amayra/arc_conv

arc_conv.exe --pack <format> <in folder> <out archive> [format specific options]

arc_conv.exe --pack qlie data data8.pack
