### ISSUE TITLE
[Game Request] 少女☆歌劇 レヴュースタァライト　舞台奏像劇　遥かなるエルドラド

### ISSUE THREAD

**Issue by red5h4d0w** [crskycode/GARbro#47]
> Game Title: Shoujo Kageki Revue Starlight Butai Souzougeki Harukanaru El Dorado
> VNDB: https://vndb.org/v41815
> Developper: Frontwing
> Engine: Kirikiri Z
> Archive file format: .xp3

Trying to open the archive files in GARbro, it says that _file could not be opened as resource archive_.

![image](https://github.com/user-attachments/assets/6ae94ff7-49c0-4f27-ab9f-6b387e82e52c)

I don't know if this project supports Kirikiri Z, but I'd really like to be able to open those archives

**Comment by Partridgemk1532** [comment]
+ I'm having the same issue as well. when i click an archive, it doesn't open or asks about the decryption key of the vn.

**Comment by crskycode** [comment]
Update the database

**Comment by red5h4d0w** [comment]
Thanks for the update, will try tonight!

**Comment by red5h4d0w** [comment]
It seems to still not work even after updating the database. (at least on my machine)

**Comment by crskycode** [comment]
GARbro cannot get the correct filename for this type of encryption scheme. If you need to get the filename, use KrkrDump instead.

**Comment by red5h4d0w** [comment]
I tried KrkrDump, but since I cannot get the game to run standalone (it crashes if not launched from Steam) I was not able to get any files from KrkrDump.

**Comment by crskycode** [comment]
1. Unpack the game exe from SteamStub. You can use steamless to do this.

2. Add "patchSbeam" and "patchSignatureCheck" to KrkrDump's config file.

```json
"patchSbeam": true,
"patchSignatureCheck": true,
```

Make sure the json file has a valid format. I will not explain anything about JSON format here.

3. Launch KrkrDump

**Comment by red5h4d0w** [comment]
Thanks for this generous info. I didn't know about steamless and those KrkrDump.json keys.
I'll try this when I get the time

**Comment by red5h4d0w** [comment]
Thanks again, I was able to use this info to extract the files.

As far as I understand, GARbro is not meant for this specific encryption scheme, so I'll close this as out of spec
