### ISSUE TITLE
[Game Request] Kono Ozora ni Tsubasa o Hirogete Cruise Sign (PlayStation 3)

### ISSUE THREAD

**Issue by DSwizzy** [crskycode/GARbro#49]
I'm trying to extract some of the files from this version of the game so i could create a uncensored/restoration patch using material from Flight Diary (since i'm certain it's based on that when they made the PS3 port) but problem is, despite that some of the files outside the se.cpk and voice.cpk opens up just fine with their audio files intact, while the image files on the other hand refuses to be read so i can't do the replacements.

is there a way you can find a way to be able to read them and then able to repack back to .cpk after making the changes?

if you need the file to see it, i can send it over real quick: https://gofile.io/d/CkclZv

**Comment by Manicsteiner** [comment]
The files in bg.cpk and ev.cpk should be compressed using lzss stream. They can be extracted and added with spc or bip suffixes, and then opened as a zip using the current version of GARbro, which will give you the original files in their uncompressed state.
The even-numbered files in ev.cpk can be manipulated in this way to get a picture file that appears to be in RGBA format, but which has about 10% redundancy, and may be handled similarly to the BIP-PS2 format, but the two are not the same. bg.cpk contains files that may be encoded as DXT or something similar, and which are only a quarter of the size of the RGBA format. The image sizes for both are written in 0x88~0x8B, Little Endian, int16 or uint16.
I'm not sure what to do next.
![图片](https://github.com/user-attachments/assets/1ac207ab-d14c-4dce-88f6-568c2c124383)

**Comment by DSwizzy** [comment]
Appreciate it, will give that tool a try, thank you very much
