### ISSUE TITLE
[Game Request] Sanoba Witch

### ISSUE THREAD

**Issue by LovelyCane** [crskycode/GARbro#52]
> Game: Sanoba Witch
VNDB: https://vndb.org/r81584
Engine: Kirikiri
Archive file format: .xp3

When I tried to open the archive files in GARbro, I used NoCrypt, Sabbat of the Witch, and Sanoba Witch , but they all appeared as gibberish after opening.
![{AEBE79F9-12D4-468C-911E-ACFE5779C98C}](https://github.com/user-attachments/assets/23330fb6-cd4b-4cfa-9824-7a41bd96ac9a)

Because GARbro have the game,so I'm not sure what's going wrong

**Comment by crskycode** [comment]
Use krkrdump instead

**Comment by LovelyCane** [comment]
Thank you for your help, now I can extract files.
