### ISSUE TITLE
[Game Request] Aku no Onna Kanbu Full Moon Night

### ISSUE THREAD

**Issue by jack-scarlet** [crskycode/GARbro#57]
Game: Aku no Onna Kanbu Full Moon Night
VNDB: https://vndb.org/r44021
Engine: DxLib
Archive file format: .med

Please add encryption support to this game.

[med_files.zip](https://github.com/user-attachments/files/17951786/med_files.zip)

**Comment by crskycode** [comment]
Did you try package edition ?

**Comment by jack-scarlet** [comment]
I don't have access to package edition.
However, I was able to extract the files I wanted with this [tool](https://github.com/morkt/GARbro/issues/484#issuecomment-952463838): 
.

Although I'm still facing some problems when editing scripts.
