### ISSUE TITLE
Game Request [Aa Mama ni Naru! ~Anata o Omotte Afureru Oppai~]

### ISSUE THREAD

**Issue by subaru471171** [crskycode/GARbro#60]
Game: Aa Mama ni Naru! ~Anata o Omotte Afureru Oppai~
VNDB: https://vndb.org/v24917
Engine: Kirikiri Game Engine
Archive file format: .bin

i have extracted the file but how do i repack it into .bin file. here the extracted folder
https://gofile.io/d/FgKLzJ

**Comment by crskycode** [comment]
![2024-12-15 155933](https://github.com/user-attachments/assets/a6684621-0f5e-41e8-8a6f-40709f1b7d25)

Choose this encryption

**Comment by subaru471171** [comment]
how do i use Garbo Mod. it doesnt open any archive.
